name: Checkmarx Add Custom Category - Python 3.8

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -vx    
    - name: List files in workspace
      run: |
        ls -la
    - name: Checkmarx SAST Scan
      uses: miguelfreitas93/checkmarx-github-action@v1.0.0
      with:
        cxAction: Scan
        cxServer: ${{ secrets.CX_SERVER }}
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: ${{ secrets.CX_TEAM }}
        cxPreset: All
        cxExcludeFolders: "tests,.vscode,.github,images,__pycache__,.pytest_cache,cxcli"
        cxExcludeFiles: "*.md,*.json,.gitignore,LICENSE"
        cxHigh: 0
        cxMedium: 0
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
